name: Package Application with PyInstaller

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller chess numpy onnxruntime

      - name: Build executable
        run: |
          pyinstaller -n dinora --onefile src/dinora/__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dinora-${{ matrix.os }}
          path: dist/dinora*
