name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"
          python-version-file: ".python_version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Ruff Lint
        run: uv run ruff check .

      - name: Ruff Format Check
        run: uv run ruff format --check .

      - name: Type Check with mypy
        run: uv run mypy .

      - name: Run Tests with pytest
        run: uv run pytest
